In [1]:
import pandas as pd 
import numpy as np
from unidecode import unidecode

In [2]:
file_path = "Resources/space_missions.csv"
encoding =  "ISO-8859-1"
space_missions_df = pd.read_csv(file_path, encoding=encoding)

In [3]:
space_missions_df.head()

,Company,Location,Date,Time,Rocket,Mission,RocketStatus,Price,MissionStatus
0,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-10-04,19:28:00,Sputnik 8K71PS,Sputnik-1,Retired,NaN,Success
1,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-11-03,02:30:00,Sputnik 8K71PS,Sputnik-2,Retired,NaN,Success
2,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",1957-12-06,16:44:00,Vanguard,Vanguard TV3,Retired,NaN,Failure
3,AMBA,"LC-26A, Cape Canaveral AFS, Florida, USA",1958-02-01,03:48:00,Juno I,Explorer 1,Retired,NaN,Success
4,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",1958-02-05,07:33:00,Vanguard,Vanguard TV3BU,Retired,NaN,Failure

In [4]:
space_missions_df["Mission"] = space_missions_df["Mission"].apply(unidecode)
space_missions_df.head()

,Company,Location,Date,Time,Rocket,Mission,RocketStatus,Price,MissionStatus
0,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-10-04,19:28:00,Sputnik 8K71PS,Sputnik-1,Retired,NaN,Success
1,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-11-03,02:30:00,Sputnik 8K71PS,Sputnik-2,Retired,NaN,Success
2,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",1957-12-06,16:44:00,Vanguard,Vanguard TV3,Retired,NaN,Failure
3,AMBA,"LC-26A, Cape Canaveral AFS, Florida, USA",1958-02-01,03:48:00,Juno I,Explorer 1,Retired,NaN,Success
4,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",1958-02-05,07:33:00,Vanguard,Vanguard TV3BU,Retired,NaN,Failure

In [5]:
unique_launch_sites = space_missions_df['Location'].unique()
unique_launch_sites

array(['Site 1/5, Baikonur Cosmodrome, Kazakhstan',
       'LC-18A, Cape Canaveral AFS, Florida, USA',
       'LC-26A, Cape Canaveral AFS, Florida, USA',
       'LC-5, Cape Canaveral AFS, Florida, USA',
       'Douglas F4D Skyray, Naval Air Station Point Mugu, California, USA',
       'SLC-17A, Cape Canaveral AFS, Florida, USA',
       'LC-11, Cape Canaveral AFS, Florida, USA',
       'SLC-1W (75-3-4), Vandenberg AFB, California, USA',
       'SLC-1E (75-3-5), Vandenberg AFB, California, USA',
       'LC-14, Cape Canaveral AFS, Florida, USA',
       'SLC-17B, Cape Canaveral AFS, Florida, USA',
       'LC-12, Cape Canaveral AFS, Florida, USA',
       'SLC-3W, Vandenberg AFB, California, USA',
       'LA-3, Wallops Flight Facility, Virginia, USA',
       'SLC-2E (75-1-1), Vandenberg AFB, California, USA',
       'SLC-3E, Vandenberg AFB, California, USA',
       'Mayak-2, Kapustin Yar, Russia',
       'LC-18B, Cape Canaveral AFS, Florida, USA',
       'SLC-36A, Cape Canaveral AFS, Florida, USA',
       'SLC-5, Vandenberg AFB, California, USA',
       'SLC-2W, Vandenberg AFB, California, USA',
       'SLC-4W, Vandenberg AFB, California, USA',
       'LC-13, Cape Canaveral AFS, Florida, USA',
       'LC-34, Cape Canaveral AFS, Florida, USA',
       'Site 31/6, Baikonur Cosmodrome, Kazakhstan',
       'LC-19, Cape Canaveral AFS, Florida, USA',
       'SLC-37B, Cape Canaveral AFS, Florida, USA',
       'SLC-4E, Vandenberg AFB, California, USA',
       'Site 41/15, Baikonur Cosmodrome, Kazakhstan',
       'SLC-20, Cape Canaveral AFS, Florida, USA',
       'Site 86/1, Kapustin Yar, Russia',
       'LC-576B3, Vandenberg AFB, California, USA',
       'SLC-40, Cape Canaveral AFS, Florida, USA',
       'Site 81/24, Baikonur Cosmodrome, Kazakhstan',
       'SLC-36B, Cape Canaveral AFS, Florida, USA',
       'Brigitte, Hammaguir, Algeria, France',
       'SLC-41, Cape Canaveral AFS, Florida, USA',
       'Site 41/1, Plesetsk Cosmodrome, Russia',
       'Site 162, Baikonur Cosmodrome, Kazakhstan',
       'Uchinoura Space Center, Japan',
       'Site 81/23, Baikonur Cosmodrome, Kazakhstan',
       'Site 133/3, Plesetsk Cosmodrome, Russia',
       'Site 161/35, Baikonur Cosmodrome, Kazakhstan',
       'SM Launch Tab, San Marco Launch Platform, Kenya',
       'Site 132/2, Plesetsk Cosmodrome, Russia',
       'Site 90/19, Baikonur Cosmodrome, Kazakhstan',
       'LC-39A, Kennedy Space Center, Florida, USA',
       'LA-5B, RAAF Woomera Range Complex, Australia',
       'LC-576A2, Vandenberg AFB, California, USA',
       'Site 90/20, Baikonur Cosmodrome, Kazakhstan',
       'Site 110/38, Baikonur Cosmodrome, Kazakhstan',
       'LC-39B, Kennedy Space Center, Florida, USA',
       'Site 191/66, Baikonur Cosmodrome, Kazakhstan',
       'Site 132/1, Plesetsk Cosmodrome, Russia',
       'Site 5020 (LA-2A), Jiuquan Satellite Launch Center, China',
       'Site 43/4, Plesetsk Cosmodrome, Russia',
       'ELD, Guiana Space Centre, French Guiana, France',
       'Mu Pad, Uchinoura Space Center, Japan',
       'Site 43/3, Plesetsk Cosmodrome, Russia',
       'Santa Rita 2, San Marco Launch Platform, Kenya',
       'Site 110/37, Baikonur Cosmodrome, Kazakhstan',
       'ELA-1, Guiana Space Centre, French Guiana, France',
       'Site 138 (LA-2B), Jiuquan Satellite Launch Center, China',
       'LC-576A1, Vandenberg AFB, California, USA',
       'Site 107/1, Kapustin Yar, Russia',
       'LA-Y1, Tanegashima Space Center, Japan',
       'Site 32/2, Plesetsk Cosmodrome, Russia',
       'SLV LP, Satish Dhawan Space Centre, India',
       'ELV-1 (SLV), Guiana Space Centre, French Guiana, France',
       'Site 32/1, Plesetsk Cosmodrome, Russia',
       'Site 16/2, Plesetsk Cosmodrome, Russia',
       'LC-3, Xichang Satellite Launch Center, China',
       'Site 45/1, Baikonur Cosmodrome, Kazakhstan',
       'ELA-2, Guiana Space Centre, French Guiana, France',
       'Site 250, Baikonur Cosmodrome, Kazakhstan',
       'Taiyuan Satellite Launch Center, China',
       'Pad 1, Palmachim Airbase, Israel',
       'SLC-N, Tanegashima Space Center, Japan',
       'NB-52B Carrier, Edwards AFB, California, USA',
       'Site 45/2, Baikonur Cosmodrome, Kazakhstan',
       'LC-2, Xichang Satellite Launch Center, China',
       'Site 131/29, Baikonur Cosmodrome, Kazakhstan',
       'Site 175/58, Baikonur Cosmodrome, Kazakhstan',
       'NB-52B Carrier, Cape Canaveral AFS, Florida, USA',
       'Site 158, Plesetsk Cosmodrome, Russia',
       'First Launch Pad, Satish Dhawan Space Centre, India',
       'SLC-576E, Vandenberg AFB, California, USA',
       'Stargazer, Vandenberg AFB, California, USA',
       'SLC-6, Vandenberg AFB, California, USA',
       'LP-0A, Wallops Flight Facility, Virginia, USA',
       'ELA-3, Guiana Space Centre, French Guiana, France',
       'Svobodny Cosmodrome, Russia',
       'Stargazer, Base Aerea de Gando, Gran Canaria',
       'LC-7, Taiyuan Satellite Launch Center, China',
       'Stargazer, Wallops Flight Facility, Virginia, USA',
       'VLS Pad, Alcântara Launch Center, Maranhão, Brazil',
       'SLC-46, Cape Canaveral AFS, Florida, USA',
       'K-407 Submarine, Barents Sea Launch Area, Barents Sea',
       'Pad 1, Tonghae Satellite Launching Ground, North Korea',
       'Stargazer, Cape Canaveral AFS, Florida, USA',
       'LP Odyssey, Kiritimati Launch Area, Pacific Ocean',
       'Site 109/95, Baikonur Cosmodrome, Kazakhstan',
       'Site 901 (SLS-1), Jiuquan Satellite Launch Center, China',
       'SLC-8, Vandenberg AFB, California, USA',
       'Stargazer, Ronald Reagan Ballistic Missile Defense Test Site, Marshall Islands, USA',
       'LP-1, Pacific Spaceport Complex, Alaska, USA',
       'Site 9401 (SLS-2), Jiuquan Satellite Launch Center, China',
       'Site 175/59, Baikonur Cosmodrome, Kazakhstan',
       'Second Launch Pad, Satish Dhawan Space Centre, India',
       'K-496 Submarine, Barents Sea Launch Area, Barents Sea',
       'Omelek Island, Ronald Reagan Ballistic Missile Defense Test Site, Marshall Islands, USA',
       'K-84 Submarine, Barents Sea Launch Area, Barents Sea',
       'Site 370/13, Yasny Cosmodrome, Russia',
       'LP-0B, Wallops Flight Facility, Virginia, USA',
       'Imam Khomeini Spaceport, Semnan Space Center, Iran',
       'LC-9, Taiyuan Satellite Launch Center, China',
       'LC-1, Naro Space Center, South Korea',
       'LA-Y2, Tanegashima Space Center, Japan',
       'ELS, Guiana Space Centre, French Guiana, France',
       'Pad 1, Sohae Satellite Launching Station, North Korea',
       'Jiuquan Satellite Launch Center, China',
       'Site 35/1, Plesetsk Cosmodrome, Russia',
       'Site 95, Jiuquan Satellite Launch Center, China',
       'Blue Origin Launch Site, West Texas, Texas, USA',
       'LC-16, Taiyuan Satellite Launch Center, China',
       'LP-41, Kauai, Pacific Missile Range Facility',
       'Site 200/39, Baikonur Cosmodrome, Kazakhstan',
       'Site 1S, Vostochny Cosmodrome, Russia',
       'LC-201, Wenchang Satellite Launch Center, China',
       'LC-101, Wenchang Satellite Launch Center, China',
       'Rocket Lab LC-1A, M?hia Peninsula, New Zealand',
       'Vertical Launch Area, Spaceport America, New Mexico',
       'Tai Rui Barge, Yellow Sea',
       'Launch Plateform, Shahrud Missile Test Site',
       'Cosmic Girl, Mojave Air and Space Port, California, USA',
       'Xichang Satellite Launch Center, China',
       'Pad A, Boca Chica, Texas, USA',
       'SLC-40, Cape Canaveral SFS, Florida, USA',
       'Rocket Lab LC-1A, MÄ\x81hia Peninsula, New Zealand',
       'ELV-1, Guiana Space Centre, French Guiana, France',
       'LP-3B, Pacific Spaceport Complex, Kodiak, Alaska, USA',
       'DeBo 3 Barge, Yellow Sea',
       'Launch Site One, West Texas, Texas, USA',
       'SLC-41, Cape Canaveral SFS, Florida, USA',
       'SLC-4E, Vandenberg SFB, California, USA',
       'Suborbital Pad A, Starbase, Texas, USA',
       'SLC-37B, Cape Canaveral SFS, Florida, USA',
       'VMS Eve, Spaceport America, New Mexico, USA',
       'Launch Platform, Shahrud Missile Test Site, Iran',
       'Suborbital Pad B, Starbase, Texas, USA',
       'SLC-6, Vandenberg SFB, California, USA',
       'Stargazer, Vandenberg SFB, California, USA',
       'SLC-2W, Vandenberg SFB, California, USA',
       'SLC-3E, Vandenberg SFB, California, USA',
       'LC-2, Naro Space Center, South Korea',
       'SLC-46, Cape Canaveral SFS, Florida, USA',
       'Rocket Lab LC-1B, MÄ\x81hia Peninsula, New Zealand',
       'LC-9A, Taiyuan Satellite Launch Center, China'], dtype=object)

In [6]:
del space_missions_df["Price"]
space_missions_df.head()

,Company,Location,Date,Time,Rocket,Mission,RocketStatus,MissionStatus
0,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-10-04,19:28:00,Sputnik 8K71PS,Sputnik-1,Retired,Success
1,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-11-03,02:30:00,Sputnik 8K71PS,Sputnik-2,Retired,Success
2,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",1957-12-06,16:44:00,Vanguard,Vanguard TV3,Retired,Failure
3,AMBA,"LC-26A, Cape Canaveral AFS, Florida, USA",1958-02-01,03:48:00,Juno I,Explorer 1,Retired,Success
4,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",1958-02-05,07:33:00,Vanguard,Vanguard TV3BU,Retired,Failure

In [7]:
space_missions_df["Time"] = space_missions_df["Time"].astype(str)

In [8]:
day_night = []

In [9]:
for row in space_missions_df["Time"]:
    first_two = row[:2]
    
    try:
        
        if int(first_two) >= 6 and int(first_two) < 18:
            day_night.append("Day")
        else: 
            day_night.append("Night")
    except ValueError:
        day_night.append("NA")

In [10]:
space_missions_df["Day/Night Launch"] = day_night
space_missions_df.head()

,Company,Location,Date,Time,Rocket,Mission,RocketStatus,MissionStatus,Day/Night Launch
0,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-10-04,19:28:00,Sputnik 8K71PS,Sputnik-1,Retired,Success,Night
1,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-11-03,02:30:00,Sputnik 8K71PS,Sputnik-2,Retired,Success,Night
2,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",1957-12-06,16:44:00,Vanguard,Vanguard TV3,Retired,Failure,Day
3,AMBA,"LC-26A, Cape Canaveral AFS, Florida, USA",1958-02-01,03:48:00,Juno I,Explorer 1,Retired,Success,Night
4,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",1958-02-05,07:33:00,Vanguard,Vanguard TV3BU,Retired,Failure,Day

In [11]:
#Cleanup of the Locations to add values or null values bef turning it into a new CSV file
#Starting with the Uchinoura Space Center, to which there are only two locations. One needs an empty space first. The other needs no
#alteration, as it already contains the value of 'Mu Pad' as the value needed.
def fix_location(location, center, excluded_rows=None):
    if excluded_rows is None:
        excluded_rows = []
    if center in location and 'Mu Pad' not in location and location not in excluded_rows:
        return f' , {center}'
    return location
space_missions_df['Location'] = space_missions_df.apply(lambda row: fix_location(row['Location'], 'Uchinoura Space Center, Japan'), axis=1)
#-----------------------------------------------------
#Exclude for the Taiyuan Satellite Launch Center
excluded_rows_taiyuan = [
    'LC-7, Taiyuan Satellite Launch Center, China',
    'LC-9, Taiyuan Satellite Launch Center, China',
    'LC-16, Taiyuan Satellite Launch Center, China',
    'LC-9A, Taiyuan Satellite Launch Center, China']
space_missions_df['Location'] = space_missions_df.apply(lambda row: fix_location(row['Location'], 'Taiyuan Satellite Launch Center, China', excluded_rows_taiyuan), axis=1)
#-----------------------------------------------------
#Exclude for the Jiuquan Satellite Launch Center
excluded_rows_jiuquan = [
    'Site 5020 (LA-2A), Jiuquan Satellite Launch Center, China',
    'Site 138 (LA-2B), Jiuquan Satellite Launch Center, China',
    'Site 901 (SLS-1), Jiuquan Satellite Launch Center, China',
    'Site 9401 (SLS-2), Jiuquan Satellite Launch Center, China',
    'Site 95, Jiuquan Satellite Launch Center, China']
space_missions_df['Location'] = space_missions_df.apply(lambda row: fix_location(row['Location'], 'Jiuquan Satellite Launch Center, China', excluded_rows_jiuquan), axis=1)
#-----------------------------------------------------
#Exclude for the Xichang Satellite Launch Center
excluded_rows_xichang = [
    'LC-3, Xichang Satellite Launch Center, China',
    'LC-2, Xichang Satellite Launch Center, China']
space_missions_df['Location'] = space_missions_df.apply(lambda row: fix_location(row['Location'], 'Xichang Satellite Launch Center, China', excluded_rows_xichang), axis=1)
#----------------------------------------------------
#Just use the str.replace for the rest of the values.
#Change Svobodny Cosmodrome, Russia, to have a space before Svobodny...
space_missions_df['Location'] = space_missions_df['Location'].str.replace('Svobodny Cosmodrome, Russia', ' , Svobodny Cosmodrome, Russia', case=False)
# Changing Hammaguir, Algeria to Hammaguir-Algeria
space_missions_df['Location'] = space_missions_df['Location'].str.replace('Brigitte, Hammaguir, Algeria, France', 'Brigitte, Hammaguir - Algeria, France', case=False)
#Need to change Guiana Space Centre, French Guiana to Guiana Space Cenre-French Guiana
space_missions_df['Location'] = space_missions_df['Location'].str.replace('ELD, Guiana Space Centre, French Guiana, France', 'ELD, Guiana Space Centre - French Guiana, France', case=False)
space_missions_df['Location'] = space_missions_df['Location'].str.replace('ELA-1, Guiana Space Centre, French Guiana, France', 'ELA-1, Guiana Space Centre - French Guiana, France', case=False)
space_missions_df['Location'] = space_missions_df['Location'].str.replace('ELV-1 (SLV), Guiana Space Centre, French Guiana, France', 'ELV-1 (SLV), Guiana Space Centre - French Guiana, France', case=False)
space_missions_df['Location'] = space_missions_df['Location'].str.replace('ELA-2, Guiana Space Centre, French Guiana, France', 'ELA-2, Guiana Space Centre - French Guiana, France', case=False)
space_missions_df['Location'] = space_missions_df['Location'].str.replace('ELA-3, Guiana Space Centre, French Guiana, France', 'ELA-3, Guiana Space Centre - French Guiana, France', case=False)
space_missions_df['Location'] = space_missions_df['Location'].str.replace('ELS, Guiana Space Centre, French Guiana, France', 'ELS, Guiana Space Centre - French Guiana, France', case=False)
space_missions_df['Location'] = space_missions_df['Location'].str.replace('ELV-1, Guiana Space Centre, French Guiana, France', 'ELV-1, Guiana Space Centre - French Guiana, France', case=False)
#Need to change Alcântara Launch Center, Maranhão to Alcântara Launch Center - Maranhão
space_missions_df['Location'] = space_missions_df['Location'].str.replace('VLS Pad, Alcântara Launch Center, Maranhão, Brazil', 'VLS Pad, Alcântara Launch Center - Maranhão, Brazil', case=False)
#Need to change Pacific Spaceport Complex, Kodiak to Pacific Spaceport Complex - Kodiak
space_missions_df['Location'] = space_missions_df['Location'].str.replace('LP-3B, Pacific Spaceport Complex, Kodiak, Alaska, USA', 'LP-3B, Pacific Spaceport Complex - Kodiak, Alaska, USA', case=False)
#Need to add USA after New Mexico
space_missions_df['Location'] = space_missions_df['Location'].str.replace('Vertical Launch Area, Spaceport America, New Mexico', 'Vertical Launch Area, Spaceport America, New Mexico, USA', case=False)
#Need to add China after Yellow Sea
space_missions_df['Location'] = space_missions_df['Location'].str.replace('Tai Rui Barge, Yellow Sea', 'Tai Rui Barge, Yellow Sea, China', case=False)
space_missions_df['Location'] = space_missions_df['Location'].str.replace('DeBo 3 Barge, Yellow Sea', 'DeBo 3 Barge, Yellow Sea, China', case=False)
#Need to fix typo in Plateform to Platfomr and add Iran at the end.
space_missions_df['Location'] = space_missions_df['Location'].str.replace('Launch Plateform, Shahrud Missile Test Site', 'Launch Platform, Shahrud Missile Test Site, Iran', case=False)
#Fixing LP-41, Kauai, Pacific Missile Range Facility to LP-41, Kauai Pacific Missile Range Facility, Hawaii, USA
space_missions_df['Location'] = space_missions_df['Location'].str.replace('LP-41, Kauai, Pacific Missile Range Facility', 'LP-41, Kauai Pacific Missile Range Facility, Hawaii, USA', case=False)
#Fixing Rocket Lab LC-1B, MÄ\x81hia Peninsula, New Zealand to: Rocket Lab LC-1B, Māhia Peninsula, New Zealand
space_missions_df['Location'] = space_missions_df['Location'].str.replace('Rocket Lab LC-1B, MÄ\x81hia Peninsula, New Zealand', 'Rocket Lab LC-1B, Mahia Peninsula, New Zealand', case=False)
#Fixing Rocket Lab LC-1A, MÄ\x81hia Peninsula, New Zealand, to: Rocket Lab LC-1A, Māhia Peninsula, New Zealand
space_missions_df['Location'] = space_missions_df['Location'].str.replace('Rocket Lab LC-1A, MÄ\x81hia Peninsula, New Zealand', 'Rocket Lab LC-1A, Mahia Peninsula, New Zealand', case=False)
space_missions_df['Location'] = space_missions_df['Location'].str.replace('Rocket Lab LC-1A, M?hia Peninsula, New Zealand', 'Rocket Lab LC-1A, Mahia Peninsula, New Zealand', case=False)

In [12]:
unique_cleanedlocation = space_missions_df['Location'].unique()
unique_cleanedlocation

array(['Site 1/5, Baikonur Cosmodrome, Kazakhstan',
       'LC-18A, Cape Canaveral AFS, Florida, USA',
       'LC-26A, Cape Canaveral AFS, Florida, USA',
       'LC-5, Cape Canaveral AFS, Florida, USA',
       'Douglas F4D Skyray, Naval Air Station Point Mugu, California, USA',
       'SLC-17A, Cape Canaveral AFS, Florida, USA',
       'LC-11, Cape Canaveral AFS, Florida, USA',
       'SLC-1W (75-3-4), Vandenberg AFB, California, USA',
       'SLC-1E (75-3-5), Vandenberg AFB, California, USA',
       'LC-14, Cape Canaveral AFS, Florida, USA',
       'SLC-17B, Cape Canaveral AFS, Florida, USA',
       'LC-12, Cape Canaveral AFS, Florida, USA',
       'SLC-3W, Vandenberg AFB, California, USA',
       'LA-3, Wallops Flight Facility, Virginia, USA',
       'SLC-2E (75-1-1), Vandenberg AFB, California, USA',
       'SLC-3E, Vandenberg AFB, California, USA',
       'Mayak-2, Kapustin Yar, Russia',
       'LC-18B, Cape Canaveral AFS, Florida, USA',
       'SLC-36A, Cape Canaveral AFS, Florida, USA',
       'SLC-5, Vandenberg AFB, California, USA',
       'SLC-2W, Vandenberg AFB, California, USA',
       'SLC-4W, Vandenberg AFB, California, USA',
       'LC-13, Cape Canaveral AFS, Florida, USA',
       'LC-34, Cape Canaveral AFS, Florida, USA',
       'Site 31/6, Baikonur Cosmodrome, Kazakhstan',
       'LC-19, Cape Canaveral AFS, Florida, USA',
       'SLC-37B, Cape Canaveral AFS, Florida, USA',
       'SLC-4E, Vandenberg AFB, California, USA',
       'Site 41/15, Baikonur Cosmodrome, Kazakhstan',
       'SLC-20, Cape Canaveral AFS, Florida, USA',
       'Site 86/1, Kapustin Yar, Russia',
       'LC-576B3, Vandenberg AFB, California, USA',
       'SLC-40, Cape Canaveral AFS, Florida, USA',
       'Site 81/24, Baikonur Cosmodrome, Kazakhstan',
       'SLC-36B, Cape Canaveral AFS, Florida, USA',
       'Brigitte, Hammaguir - Algeria, France',
       'SLC-41, Cape Canaveral AFS, Florida, USA',
       'Site 41/1, Plesetsk Cosmodrome, Russia',
       'Site 162, Baikonur Cosmodrome, Kazakhstan',
       ' , Uchinoura Space Center, Japan',
       'Site 81/23, Baikonur Cosmodrome, Kazakhstan',
       'Site 133/3, Plesetsk Cosmodrome, Russia',
       'Site 161/35, Baikonur Cosmodrome, Kazakhstan',
       'SM Launch Tab, San Marco Launch Platform, Kenya',
       'Site 132/2, Plesetsk Cosmodrome, Russia',
       'Site 90/19, Baikonur Cosmodrome, Kazakhstan',
       'LC-39A, Kennedy Space Center, Florida, USA',
       'LA-5B, RAAF Woomera Range Complex, Australia',
       'LC-576A2, Vandenberg AFB, California, USA',
       'Site 90/20, Baikonur Cosmodrome, Kazakhstan',
       'Site 110/38, Baikonur Cosmodrome, Kazakhstan',
       'LC-39B, Kennedy Space Center, Florida, USA',
       'Site 191/66, Baikonur Cosmodrome, Kazakhstan',
       'Site 132/1, Plesetsk Cosmodrome, Russia',
       'Site 5020 (LA-2A), Jiuquan Satellite Launch Center, China',
       'Site 43/4, Plesetsk Cosmodrome, Russia',
       'ELD, Guiana Space Centre - French Guiana, France',
       'Mu Pad, Uchinoura Space Center, Japan',
       'Site 43/3, Plesetsk Cosmodrome, Russia',
       'Santa Rita 2, San Marco Launch Platform, Kenya',
       'Site 110/37, Baikonur Cosmodrome, Kazakhstan',
       'ELA-1, Guiana Space Centre - French Guiana, France',
       'Site 138 (LA-2B), Jiuquan Satellite Launch Center, China',
       'LC-576A1, Vandenberg AFB, California, USA',
       'Site 107/1, Kapustin Yar, Russia',
       'LA-Y1, Tanegashima Space Center, Japan',
       'Site 32/2, Plesetsk Cosmodrome, Russia',
       'SLV LP, Satish Dhawan Space Centre, India',
       'ELV-1 (SLV), Guiana Space Centre - French Guiana, France',
       'Site 32/1, Plesetsk Cosmodrome, Russia',
       'Site 16/2, Plesetsk Cosmodrome, Russia',
       'LC-3, Xichang Satellite Launch Center, China',
       'Site 45/1, Baikonur Cosmodrome, Kazakhstan',
       'ELA-2, Guiana Space Centre - French Guiana, France',
       'Site 250, Baikonur Cosmodrome, Kazakhstan',
       ' , Taiyuan Satellite Launch Center, China',
       'Pad 1, Palmachim Airbase, Israel',
       'SLC-N, Tanegashima Space Center, Japan',
       'NB-52B Carrier, Edwards AFB, California, USA',
       'Site 45/2, Baikonur Cosmodrome, Kazakhstan',
       'LC-2, Xichang Satellite Launch Center, China',
       'Site 131/29, Baikonur Cosmodrome, Kazakhstan',
       'Site 175/58, Baikonur Cosmodrome, Kazakhstan',
       'NB-52B Carrier, Cape Canaveral AFS, Florida, USA',
       'Site 158, Plesetsk Cosmodrome, Russia',
       'First Launch Pad, Satish Dhawan Space Centre, India',
       'SLC-576E, Vandenberg AFB, California, USA',
       'Stargazer, Vandenberg AFB, California, USA',
       'SLC-6, Vandenberg AFB, California, USA',
       'LP-0A, Wallops Flight Facility, Virginia, USA',
       'ELA-3, Guiana Space Centre - French Guiana, France',
       ' , Svobodny Cosmodrome, Russia',
       'Stargazer, Base Aerea de Gando, Gran Canaria',
       'LC-7, Taiyuan Satellite Launch Center, China',
       'Stargazer, Wallops Flight Facility, Virginia, USA',
       'VLS Pad, Alcântara Launch Center - Maranhão, Brazil',
       'SLC-46, Cape Canaveral AFS, Florida, USA',
       'K-407 Submarine, Barents Sea Launch Area, Barents Sea',
       'Pad 1, Tonghae Satellite Launching Ground, North Korea',
       'Stargazer, Cape Canaveral AFS, Florida, USA',
       'LP Odyssey, Kiritimati Launch Area, Pacific Ocean',
       'Site 109/95, Baikonur Cosmodrome, Kazakhstan',
       'Site 901 (SLS-1), Jiuquan Satellite Launch Center, China',
       'SLC-8, Vandenberg AFB, California, USA',
       'Stargazer, Ronald Reagan Ballistic Missile Defense Test Site, Marshall Islands, USA',
       'LP-1, Pacific Spaceport Complex, Alaska, USA',
       'Site 9401 (SLS-2), Jiuquan Satellite Launch Center, China',
       'Site 175/59, Baikonur Cosmodrome, Kazakhstan',
       'Second Launch Pad, Satish Dhawan Space Centre, India',
       'K-496 Submarine, Barents Sea Launch Area, Barents Sea',
       'Omelek Island, Ronald Reagan Ballistic Missile Defense Test Site, Marshall Islands, USA',
       'K-84 Submarine, Barents Sea Launch Area, Barents Sea',
       'Site 370/13, Yasny Cosmodrome, Russia',
       'LP-0B, Wallops Flight Facility, Virginia, USA',
       'Imam Khomeini Spaceport, Semnan Space Center, Iran',
       'LC-9, Taiyuan Satellite Launch Center, China',
       'LC-1, Naro Space Center, South Korea',
       'LA-Y2, Tanegashima Space Center, Japan',
       'ELS, Guiana Space Centre - French Guiana, France',
       'Pad 1, Sohae Satellite Launching Station, North Korea',
       ' , Jiuquan Satellite Launch Center, China',
       'Site 35/1, Plesetsk Cosmodrome, Russia',
       'Site 95, Jiuquan Satellite Launch Center, China',
       'Blue Origin Launch Site, West Texas, Texas, USA',
       'LC-16, Taiyuan Satellite Launch Center, China',
       'LP-41, Kauai Pacific Missile Range Facility, Hawaii, USA',
       'Site 200/39, Baikonur Cosmodrome, Kazakhstan',
       'Site 1S, Vostochny Cosmodrome, Russia',
       'LC-201, Wenchang Satellite Launch Center, China',
       'LC-101, Wenchang Satellite Launch Center, China',
       'Rocket Lab LC-1A, Mahia Peninsula, New Zealand',
       'Vertical Launch Area, Spaceport America, New Mexico, USA',
       'Tai Rui Barge, Yellow Sea, China',
       'Launch Platform, Shahrud Missile Test Site, Iran',
       'Cosmic Girl, Mojave Air and Space Port, California, USA',
       ' , Xichang Satellite Launch Center, China',
       'Pad A, Boca Chica, Texas, USA',
       'SLC-40, Cape Canaveral SFS, Florida, USA',
       'ELV-1, Guiana Space Centre - French Guiana, France',
       'LP-3B, Pacific Spaceport Complex - Kodiak, Alaska, USA',
       'DeBo 3 Barge, Yellow Sea, China',
       'Launch Site One, West Texas, Texas, USA',
       'SLC-41, Cape Canaveral SFS, Florida, USA',
       'SLC-4E, Vandenberg SFB, California, USA',
       'Suborbital Pad A, Starbase, Texas, USA',
       'SLC-37B, Cape Canaveral SFS, Florida, USA',
       'VMS Eve, Spaceport America, New Mexico, USA',
       'Suborbital Pad B, Starbase, Texas, USA',
       'SLC-6, Vandenberg SFB, California, USA',
       'Stargazer, Vandenberg SFB, California, USA',
       'SLC-2W, Vandenberg SFB, California, USA',
       'SLC-3E, Vandenberg SFB, California, USA',
       'LC-2, Naro Space Center, South Korea',
       'SLC-46, Cape Canaveral SFS, Florida, USA',
       'Rocket Lab LC-1B, Mahia Peninsula, New Zealand',
       'LC-9A, Taiyuan Satellite Launch Center, China'], dtype=object)

In [13]:
space_missions_df.to_csv('Resources/SpaceMission_cleanedLocFinal.csv', index=False)